# Generated by Django 3.2.7 on 2021-09-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rate')),
            ],
            options={
                'verbose_name': 'Base',
                'verbose_name_plural': 'Base',
            },
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
